id: P62A98624
initial_creation_type: ocr
source_metadata:
  volumes:
    f264db8df82c483f9d7b0acc3112a849:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཕྱག་ན་རྡོ་རྗེའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1379
      volume_number: 37
